version: '3'
services:

  app:
    container_name: api
    build: .
    ports: 
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: postgres:latest
    build:
        context: .
        dockerfile: Dockerfile.postgres
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5434:5434'
    volumes:
      - ./data/db:/var/lib/postgresql/data

  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - 27017:27017
    restart: unless-stopped